version: 0.2

phases:

  install:
    commands:
      - echo Installing dependencies...

  build:
    commands:
      - echo Building application...
      - mkdir output
      - cp index.html appspec.yml output/

artifacts:
  files:
    - '**/*'
  base-directory: output
